apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# 개발 환경에만 붙일 접미사나 네임스페이스 설정
namePrefix: dev-

# 개발 환경용 이미지 태그 고정
images:
  - name: registry.ocp.test.com:5000/demo/test-project
    newTag: 235c0131d001952551a1a11c74dc4c8c7bd524bc
