apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: test-project
  template:
    metadata:
      labels:
        app: test-project
    spec:
      containers:
      - name: test-project
        # 우리가 Tekton으로 빌드한 바로 그 이미지 주소!
        image: registry.ocp.test.com:5000/demo/test-project:latest
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret     # 아까 만든 시크릿 이름
              key: OPENAI_API_KEY    # 시크릿 안의 키 이름
        ports:
        - containerPort: 8080