apiVersion: v1
kind: Service
metadata:
  name: test-project-service
  namespace: demo
spec:
  selector:
    app: test-project      # Deployment의 labels와 똑같아야 합니다! (Deployment와 일치)
  ports:
    - protocol: TCP
      port: 80           # 서비스가 사용하는 포트
      targetPort: 8080   # 실제 컨테이너(Pod)가 듣고 있는 포트
  type: ClusterIP